### ISSUE TITLE
Sending TTL w/ Binary Format

### ISSUE THREAD

**Issue by markschatza** [open-ephys-plugins/network-events#1]
Hello!

I added the TTL functionality awhile ago. It seems that it isn't working with Binary file format or with the new record node. Not sure if it's a network events issue or a binary format issue. The message events are going through, but the TTL events are not being triggered.

**Comment by jsiegle** [comment]
This is likely related to an issue with the underlying Record Node connections that we're in the process of fixing. @medengineer, can you test out this use case?

**Comment by jsiegle** [comment]
This should be fixed in the latest test binaries: https://dl.bintray.com/open-ephys-gui/Test/

Can you check if it's working now?

**Comment by markschatza** [comment]
I don't think so? I used v0.5 and then used the plugin installer to install network events. I then sent ttl events over (which show up in the message area in the plugin gui). When I load in the structure.oebin file through load_open_ephys_binary I get the correct number of events. But the channelindex is 1 for all of them so I think they are just mesage events, but not the ttls. I'm sending one ttl event to each of the 8 channels.

**Comment by medengineer** [comment]
Hi Mark,

Are you using a similar chain as below? It should also work with a NetworkEvents module going into a Record Node by itself. 

![NetworkEventsWithMerger](https://user-images.githubusercontent.com/10275396/93505439-b6fa5800-f8cf-11ea-8204-bca2a1a1145c.png)

**Comment by markschatza** [comment]
Oh I see. Yep, I get exactly that. My problem was I didn't understand exactly how to use the load_open_ephys_binary() function. I wasn't changing the index based on my signal chain. Updated the index and works great.

Thanks for clarifying! :)
